FROM python:3.13

RUN apt update
RUN apt install gcc libpq-dev

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

RUN pip install poetry
RUN poetry config virtualenvs.create false

WORKDIR /app

COPY . .

RUN poetry install --no-root

ENV PATH="/opt/venv/bin:$PATH"


CMD ["poetry", "run", "alembic", "upgrade", "head"]


